# Generated by Django 3.2.7 on 2021-09-30 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_block_candidat_electeur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electeur',
            name='id_electeur',
            field=models.CharField(max_length=200),
        ),
    ]
