# Generated by Django 3.2.7 on 2021-09-30 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_electeur_id_electeur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='hashSuivant',
        ),
        migrations.RemoveField(
            model_name='block',
            name='id_block',
        ),
        migrations.AddField(
            model_name='electeur',
            name='a_vote',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='parti',
            field=models.CharField(max_length=30),
        ),
    ]
